# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: rossoskull.me
name-title: "Jay Mistry"
email: mistry.jay15@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey everyone! I am Jay Mistry, a sophomore at IIIT Vadodara. I got into coding a bit early in
   my life, and am loving it since then! I love learning new stuff, and building things that help 
   out me, and others. I believe in building a solution, rather than finding it someplace else. You 
   can know more about me on one of my social handles. Thanks for visiting!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rossoskull.me" # the base hostname & protocol for your site
twitter_username: rossoskull
github_username:  rossoskull
insta_username: rossoskull

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight